version: '3.8'
services:
  postgres:
    container_name: postgres 
    image: postgres:11.6
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: ecom_db
    networks:
    - my_network
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dbuser@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1991
    ports:
      - 5050:80
    depends_on:
      - postgres
      - web
    networks:
    - my_network 

  web:
    restart: always
    container_name: web
    environment:
      - DJANGO_SECRET_KEY='django-insecure-guysx2yy9!%uvle=$mo35rba=rmt#j*6rs!s51!!_t4^6i(h1)'
    build: 
      context: ./src
      dockerfile: Dockerfile
         # python wait_for_postgres.py &&
    command: >
      bash -c " 
                python manage.py makemigrations ;
                python manage.py migrate ;
                python manage.py runserver 0.0.0.0:8000 ;
                "
               
                
             
    volumes:
    #  ./manage.py makemigrations &&
    # ./manage.py runserver 0.0.0.0:8000"
      # - ./:/code
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      # - redis
    networks:
    - my_network

  # redis:
  #     container_name: redis
  #     image: redis:6.2-alpine
  #     restart: always
  #     # network_mode: 172.22.0.3
  #     ports:
  #       - '6379:6379'
  #     # tty: true
  #     command: redis-server --save 20 1 --loglevel warning
  #     volumes:
  #       - cache-redis:/data
  #     networks:
  #       - my_network    