# Generated by Django 4.0.1 on 2024-07-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesByCardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.IntegerField()),
                ('card_type', models.CharField(max_length=50)),
                ('total_sales', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesByCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('total_sales', models.FloatField()),
            ],
        ),
    ]
